// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Sb8OOnzy9Uc2deJqlnW9n99PSLp-fqQ',
    appId: '1:723601137743:web:c035e70b5f6f434f4d4a3a',
    messagingSenderId: '723601137743',
    projectId: 'ticket-app-6a86d',
    authDomain: 'ticket-app-6a86d.firebaseapp.com',
    storageBucket: 'ticket-app-6a86d.firebasestorage.app',
    measurementId: 'G-LC5CMY97EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAg1XuYCSjodcpMv-cm5PNG1IfmLZoa0A',
    appId: '1:723601137743:android:90dc08a27cb2160c4d4a3a',
    messagingSenderId: '723601137743',
    projectId: 'ticket-app-6a86d',
    storageBucket: 'ticket-app-6a86d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3VI5vYiHF2yvv4JaZ7LIU4S_qAwOBJpk',
    appId: '1:723601137743:ios:38bd545f8cfa451a4d4a3a',
    messagingSenderId: '723601137743',
    projectId: 'ticket-app-6a86d',
    storageBucket: 'ticket-app-6a86d.firebasestorage.app',
    iosBundleId: 'com.example.ticketingApp',
  );
}
